image: ralfjung/opam-ci:latest

stages:
  - build

variables:
  CPU_CORES: "9"

.template: &template
  stage: build
  tags:
  - fp-timing
  script:
  # prepare
  - . build/opam-ci.sh $OPAM_PINS
  - env | egrep '^(CI_BUILD_REF|CI_RUNNER)' > build-env.txt
  # build
  - 'time make -k -j$CPU_CORES TIMED=y 2>&1 | tee build-log.txt'
  - 'if fgrep Axiom build-log.txt >/dev/null; then exit 1; fi'
  - 'cat build-log.txt | egrep "[a-zA-Z0-9_/-]+ \((real|user): [0-9]" | tee build-time.txt'
  - 'if test -n "$VALIDATE" && (( RANDOM % 10 == 0 )); then make validate; fi'
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  only:
  - master
  - /^ci/

build-coq.8.7.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.0   coq-mathcomp-ssreflect version 1.6.2"
  except:
  - triggers

build-coq.8.6.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.6.1   coq-mathcomp-ssreflect version 1.6.2"
#    VALIDATE: "1" # coqchk on lambdaRust is currently broken, see Coq bug #5747
  artifacts:
    paths:
    - build-time.txt
    - build-env.txt
  except:
  - triggers

build-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.6.1   coq-mathcomp-ssreflect version 1.6.2   coq-iris.dev git https://gitlab.mpi-sws.org/FP/iris-coq.git#$IRIS_REV"
  only:
  - triggers
