image: ralfjung/opam-ci:latest

lrust-coq8.6:
  script:
  # prepare
  - . build/opam-ci.sh 'coq 8.6' 'coq-mathcomp-ssreflect 1.6.1'
  # build
  - 'time make -j8'
  cache:
    key: "coq8.6"
    paths:
    - opamroot/
  only:
  - master
  - ci
