image: ralfjung/opam-ci:latest

lrust-coq8.5.3:
  tags:
  - coq
  script:
  # prepare
  - . build/opam-ci.sh 'coq 8.5.3' 'coq-mathcomp-ssreflect 1.6'
  # build
  - 'time make -j8'
  cache:
    key: "coq8.5.3-2"
    paths:
    - opamroot/
  only:
  - master
  - ci
