image: ralfjung/opam-ci:latest

variables:
  CPU_CORES: "9"

lrust-coq8.6:
  tags:
  - fp-timing
  script:
  # prepare
  - . build/opam-ci.sh coq 8.6 coq-mathcomp-ssreflect 1.6.1
  - env | egrep '^(CI_BUILD_REF|CI_RUNNER)' > build-env.txt
  # build
  - 'time make -j$CPU_CORES TIMED=y 2>&1 | tee build-log.txt'
  - 'if fgrep Axiom build-log.txt >/dev/null; then exit 1; fi'
  - 'cat build-log.txt | egrep "[a-zA-Z0-9_/-]+ \(user: [0-9]" | tee build-time.txt'
  cache:
    key: "coq8.6"
    paths:
    - opamroot/
  only:
  - master
  - /^ci/
  artifacts:
    paths:
    - build-time.txt
    - build-env.txt
