image: coq:8.5

stages:
  - iris
  - lrust

iris:
  stage: iris
  tags:
  - coq
  script:
  - coqc -v
  # see if the Iris submodule needs cleaning, then build it
  - 'git submodule status iris | egrep "^ " || (git submodule update --init iris && cd iris && git clean -xfd)'
  - 'cd iris && make -j8'
  only:
  - master
  - ci

lrust:
  stage: lrust
  tags:
  - coq
  script:
  - coqc -v
  # prepare the environment
  - 'ln -s iris iris-enabled'
  # build local repo
  - 'time make -j8'
  only:
  - master
  - ci
