image: ralfjung/opam-ci:latest

stages:
  - build

variables:
  CPU_CORES: "10"
  GIT_SUBMODULE_STRATEGY: "recursive"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  only:
  - master
  - /^ci/
  except:
  - triggers
  - schedules

## Build jobs

build-coq.8.8.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.8.0"
    OPAM_PKG: "coq-lambda-rust"
    TIMING_PROJECT: "lambda-rust"
    TIMING_CONF: "coq-8.8.0"
  tags:
  - fp-timing

build-coq.8.7.2:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.2"
    TIMING_PROJECT: "lambda-rust"
    TIMING_CONF: "coq-8.7.2"
  tags:
  - fp-timing

build-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.2   coq-iris.dev git https://gitlab.mpi-sws.org/FP/iris-coq.git#$IRIS_REV"
  except:
  only:
  - triggers
  - schedules
